version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourvibes123
      POSTGRES_DB: yourvibes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"

  yourvibes_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: yourvibes_api_server:latest
    container_name: yourvibes_api_server
    restart: on-failure
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    volumes:
      - yourvibes_storage:/storages
      - tmp_volume:/tmp

volumes:
  postgres_data:
  yourvibes_storage:
  tmp_volume:
